# Generated by Django 4.0.5 on 2022-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(verbose_name='Text of Article')),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
